trigger: none

jobs:
- deployment: core_monolith_release_server
  environment: Server
  pool:
    name: Default

  workspace:
    clean: all

  strategy:
    runOnce:
      deploy:
        steps:

        - checkout: self
          displayName: 'Sync source'
          clean: true
          fetchTags: true
          fetchDepth: 0