trigger: 
 - master

jobs:
- job: core_monolith_build_sonar
  pool:
    name: Default

  workspace:
    clean: all

  variables:
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'

  steps:
  - checkout: self
    displayName: 'Sync source'
    clean: true
    fetchTags: true
    fetchDepth: 0

  - task: UseDotNet@2
    displayName: 'Enable .Net'
    inputs:
      packageType: 'sdk'
      version: '9.0.x'
      performMultiLevelLookup: true

  - task: DotNetCoreCLI@2
    displayName: 'Build solution'
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: 'Run unit tests with code coverage'
    inputs:
      command: 'test'
      projects: '**/*tests/*.csproj'
      arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'